"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type Severity="none"|"mild"|"moderate"|"severe"; type Status="open"|"treated"|"resolved";
type Scan={id:string;field:string;crop:string;disease:string|null;pest:string|null;severity:Severity;health:number;status:Status;created:string;recommendation:string;source:string};
type Field={id:string;name:string;crop:string;area:number;moisture:number;health:number;stage:string;yield:number};
type Alert={id:string;title:string;type:string;severity:"low"|"medium"|"high"|"critical";message:string;status:"active"|"resolved"};
type Treatment={id:string;action:string;scanId:string;created:string;notes:string};

const seedFields:Field[]=[
{id:"F-01",name:"North Tomato Block",crop:"Tomato",area:2.8,moisture:48,health:86,stage:"Flowering",yield:4200},
{id:"F-02",name:"East Rice Plot",crop:"Rice",area:4.2,moisture:67,health:78,stage:"Tillering",yield:5100},
{id:"F-03",name:"South Wheat Block",crop:"Wheat",area:3.5,moisture:39,health:61,stage:"Grain filling",yield:3300},
{id:"F-04",name:"West Cotton Block",crop:"Cotton",area:5.1,moisture:54,health:91,stage:"Boll formation",yield:1900},
];
const seedScans:Scan[]=[
{id:"S-104",field:"North Tomato Block",crop:"Tomato",disease:null,pest:"Aphids",severity:"mild",health:84,status:"treated",created:new Date(Date.now()-3600000).toISOString(),recommendation:"Monitor leaf undersides and use an approved targeted control if the population increases.",source:"camera"},
{id:"S-103",field:"South Wheat Block",crop:"Wheat",disease:"Leaf Rust",pest:null,severity:"moderate",health:58,status:"open",created:new Date(Date.now()-7200000).toISOString(),recommendation:"Remove heavily affected leaves where practical and follow local fungicide guidance.",source:"upload"},
{id:"S-102",field:"East Rice Plot",crop:"Rice",disease:null,pest:null,severity:"none",health:92,status:"resolved",created:new Date(Date.now()-86400000).toISOString(),recommendation:"No disease signal detected. Continue routine scouting.",source:"camera"},
];
const seedAlerts:Alert[]=[
{id:"A-1",title:"Leaf rust pressure rising",type:"disease",severity:"high",message:"South Wheat Block has a moderate disease signal.",status:"active"},
{id:"A-2",title:"Irrigation recommended",type:"irrigation",severity:"medium",message:"Soil moisture in the South Wheat Block is below the preferred range.",status:"active"},
];
const crops=["Tomato","Wheat","Rice","Corn","Potato","Cotton","Soybean","Grape"];
const nav=[['dashboard','Dashboard'],['scan','Scan Crop'],['map','Farm Map'],['analytics','Analytics'],['history','History'],['admin','Admin']];
function load<T>(key:string,fallback:T):T{if(typeof window==='undefined')return fallback;try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function save(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function pill(s:string){return <span className={`pill ${s==='none'||s==='resolved'||s==='treated'||s==='healthy'?'healthy':s==='mild'||s==='medium'?'warning':'danger'}`}>{s==='none'?'healthy':s}</span>}

export default function CropDoctor(){
 const [section,setSection]=useState("dashboard"); const [fields]=useState(seedFields); const [scans,setScans]=useState<Scan[]>(seedScans); const [alerts,setAlerts]=useState<Alert[]>(seedAlerts); const [treatments,setTreatments]=useState<Treatment[]>([]); const [now,setNow]=useState(new Date()); const [toast,setToast]=useState(""); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState(""); const [crop,setCrop]=useState("Tomato"); const [fieldId,setFieldId]=useState("F-01"); const [result,setResult]=useState<Scan|null>(null); const [admin,setAdmin]=useState(false); const [user,setUser]=useState(""); const [pass,setPass]=useState(""); const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{setScans(load("cd_scans",seedScans));setAlerts(load("cd_alerts",seedAlerts));setTreatments(load("cd_treatments",[]));setAdmin(sessionStorage.getItem("cd_admin")==="1")},[]);
 useEffect(()=>{save("cd_scans",scans)},[scans]); useEffect(()=>{save("cd_alerts",alerts)},[alerts]); useEffect(()=>{save("cd_treatments",treatments)},[treatments]);
 useEffect(()=>{const id=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(id)},[]); useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),3000);return()=>clearTimeout(id)},[toast]);
 const avg=useMemo(()=>fields.reduce((a,f)=>a+f.health,0)/fields.length,[fields]); const activeAlerts=alerts.filter(a=>a.status==='active').length; const healthy=useMemo(()=>scans.length?Math.round(scans.filter(s=>s.severity==='none').length/scans.length*100):0,[scans]);
 function chooseFile(f:File){if(!f.type.startsWith('image/')){setToast('Please choose an image file.');return}setFile(f);setPreview(URL.createObjectURL(f));setResult(null)}
 function analyze(){if(!file){setToast('Upload a crop image first.');return}const risky=file.size%5===0;const selected=fields.find(f=>f.id===fieldId)||fields[0];const disease=risky?(crop==='Wheat'?'Leaf Rust':crop==='Tomato'?'Early Blight':'Leaf Spot'):null;const severity:Severity=risky?'moderate':'none';const health=risky?61+(file.size%18):87+(file.size%9);const scan:Scan={id:`S-${Date.now().toString().slice(-6)}`,field:selected.name,crop,disease,pest:risky&&crop==='Tomato'?'Aphids':null,severity,health,status:risky?'open':'resolved',created:new Date().toISOString(),recommendation:risky?'Isolate the affected area, scout nearby plants, and follow locally approved treatment guidance.':'No significant disease signal detected. Continue routine scouting and balanced irrigation.',source:'upload'};setResult(scan);setScans(s=>[scan,...s]);if(risky){setAlerts(a=>[{id:`A-${Date.now()}`,title:`${disease} detected`,type:'disease',severity:'high',message:`${selected.name} needs follow-up.`,status:'active'},...a]);setToast('Diagnosis complete — follow-up alert created.')}else setToast('Diagnosis complete — crop looks healthy.')}
 function resolveAlert(id:string){setAlerts(a=>a.map(x=>x.id===id?{...x,status:'resolved'}:x));setToast('Alert resolved.')}
 function setScanStatus(id:string,status:Status){setScans(s=>s.map(x=>x.id===id?{...x,status}:x));setToast(`Scan marked ${status}.`)}
 function login(e:React.FormEvent){e.preventDefault();if(user==='admin'&&pass==='cropdoctor'){sessionStorage.setItem('cd_admin','1');setAdmin(true);setToast('Admin mode enabled.')}else setToast('Demo login: admin / cropdoctor')}
 function logout(){sessionStorage.removeItem('cd_admin');setAdmin(false);setUser('');setPass('')}
 function resetDemo(){localStorage.removeItem('cd_scans');localStorage.removeItem('cd_alerts');localStorage.removeItem('cd_treatments');setScans(seedScans);setAlerts(seedAlerts);setTreatments([]);setToast('Demo data reset.')}
 const healthBars=[86,84,82,79,76,78,81,Math.round(avg),Math.max(50,Math.round(avg-3)),Math.round(avg+2)];
 return <div className="app">
  <aside className="sidebar"><div className="brand"><div className="logo">🌱</div><div><b>Crop Doctor</b><small>AI Farm Intelligence</small></div></div><nav className="nav">{nav.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</nav><div className="status"><span className="dot"/>Local demo mode · data persists in this browser<br/><span style={{display:'block',marginTop:6}}>Vercel-ready — no API key required.</span></div></aside>
  <main className="main"><div className="top"><div><h1>{nav.find(n=>n[0]===section)?.[1]}</h1><p>Monitor crops, detect problems early, and make faster farm decisions.</p></div><div className="clock">{now.toLocaleString()}</div></div>
  <section className={`section ${section==='dashboard'?'active':''}`}>
   <div className="card hero" style={{marginBottom:16}}><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center'}}><div><span className="pill">Operational</span><h2 style={{fontSize:24,margin:'12px 0 5px'}}>Farm health is under control.</h2><p style={{margin:0,maxWidth:650}}>Crop Doctor combines field health, scan history, irrigation signals and alerts in one lightweight dashboard. Try the scan workflow to create live local records.</p></div><div className="kpi"><b>{Math.round(avg)}</b><br/>average health</div></div></div>
   <div className="grid stats"><div className="card stat"><div className="label">Average crop health</div><div className="value">{Math.round(avg)}</div><div className="trend">↑ 4.2% vs last cycle</div></div><div className="card stat"><div className="label">Active alerts</div><div className="value">{activeAlerts}</div><div className="trend" style={{color:activeAlerts?'#d97706':'#15803d'}}>{activeAlerts?'Action recommended':'All clear'}</div></div><div className="card stat"><div className="label">Scans completed</div><div className="value">{scans.length}</div><div className="trend">Local history</div></div><div className="card stat"><div className="label">Healthy scan rate</div><div className="value">{healthy}%</div><div className="trend">Continuous scouting</div></div></div>
   <div className="grid two" style={{marginTop:16}}><div className="card"><h2>Priority alerts</h2><div className="list">{alerts.filter(a=>a.status==='active').slice(0,5).map(a=><div className="row" key={a.id}><div><strong>{a.title}</strong><br/><span>{a.message}</span></div>{pill(a.severity)}</div>)}{!activeAlerts&&<div className="empty">No active alerts.</div>}</div></div><div className="card"><h2>Field health</h2><div className="list">{fields.map(f=><div className="row" key={f.id}><div><strong>{f.name}</strong><br/><span>{f.crop} · {f.moisture}% moisture</span></div>{pill(f.health>=80?'healthy':f.health>=60?'mild':'high')}</div>)}</div></div></div>
  </section>
  <section className={`section ${section==='scan'?'active':''}`}><div className="grid two"><div className="card"><h2>AI crop diagnosis</h2><div className="form"><label>Field<select className="input" value={fieldId} onChange={e=>setFieldId(e.target.value)}>{fields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Crop<select className="input" value={crop} onChange={e=>setCrop(e.target.value)}>{crops.map(c=><option key={c}>{c}</option>)}</select></label><label className="upload" onClick={()=>input.current?.click()}><div style={{fontSize:30}}>📷</div><b>{file?file.name:'Upload leaf or crop photo'}</b><div className="note">JPG, PNG, WEBP · analysis runs locally in demo mode</div><input ref={input} type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)chooseFile(f)}}/></label>{preview&&<img src={preview} className="preview" alt="Selected crop"/>}<button className="btn" onClick={analyze}>{result?'Run another diagnosis':'Run AI diagnosis'}</button><div className="note">Demo detector is deterministic and intentionally labeled as a simulation. For production accuracy, connect this UI to your trained vision model/API.</div></div></div><div className="card"><h2>Diagnosis result</h2>{!result?<div className="empty">Upload an image and run diagnosis to see health, disease and treatment guidance.</div>:<div className="result"><div style={{display:'flex',alignItems:'center',gap:14}}><div className="health" style={{['--score' as string]:`${result.health}%`}}><b>{result.health}</b></div><div><h3 style={{margin:0}}>{result.field}</h3><span style={{color:'#77817a',fontSize:12}}>{result.crop}</span></div>{pill(result.severity)}</div><hr style={{border:0,borderTop:'1px solid #e3e8e3',margin:'15px 0'}}/><p><b>{result.disease||'No disease detected'}</b>{result.pest?` · ${result.pest}`:''}</p><p className="note">{result.recommendation}</p><div className="progress"><i style={{width:`${result.health}%`}}/></div><p className="note" style={{marginBottom:0}}>Health signal: {result.health}/100</p></div>}</div></div></section>
  <section className={`section ${section==='map'?'active':''}`}><div className="grid two"><div className="card"><h2>Farm map</h2><div className="field-map">{fields.map((f,i)=><div key={f.id} className="field-shape" style={{left:`${8+i*21}%`,top:`${10+(i%2)*38}%`,width:`${18+i*2}%`,height:`${24+(i%3)*7}%`}}>{f.name.replace(' Block','').replace(' Plot','')}<span className="marker" style={{right:-7,top:-7,background:f.health>=80?'#22c55e':f.health>=60?'#f59e0b':'#ef4444'}}/></div>)}</div></div><div className="card"><h2>Field details</h2><div className="list">{fields.map(f=><div className="row" key={f.id}><div><strong>{f.name}</strong><br/><span>{f.crop} · {f.area} ha · {f.stage}</span></div><div style={{textAlign:'right'}}><b>{Math.round(f.health)}</b><br/><span>{f.moisture}% moisture</span></div></div>)}</div></div></div></section>
  <section className={`section ${section==='analytics'?'active':''}`}><div className="grid stats"><div className="card stat"><div className="label">Expected yield</div><div className="value">{(fields.reduce((a,f)=>a+f.yield*f.area,0)/1000).toFixed(1)}t</div><div className="trend">Current field forecast</div></div><div className="card stat"><div className="label">Disease scans</div><div className="value">{scans.filter(s=>s.disease).length}</div><div className="trend">Early warning signals</div></div><div className="card stat"><div className="label">Pest scans</div><div className="value">{scans.filter(s=>s.pest).length}</div><div className="trend">Scouting signals</div></div><div className="card stat"><div className="label">Fields monitored</div><div className="value">{fields.length}</div><div className="trend">{fields.reduce((a,f)=>a+f.area,0).toFixed(1)} hectares</div></div></div><div className="grid two" style={{marginTop:16}}><div className="card"><h2>Health trend</h2><div className="chart">{healthBars.map((v,i)=><div key={i} className="bar" style={{height:`${Math.max(18,v-20)}%`}}><small>{v}</small></div>)}</div></div><div className="card"><h2>Crop health comparison</h2><div className="list">{fields.map(f=><div key={f.id}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,marginBottom:5}}><span>{f.crop}</span><b>{Math.round(f.health)}</b></div><div className="progress"><i style={{width:`${f.health}%`}}/></div></div>)}</div></div></div></section>
  <section className={`section ${section==='history'?'active':''}`}><div className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><h2 style={{margin:0}}>Scan history</h2><button className="btn secondary" onClick={()=>{setScans(seedScans);setToast('Scan history reset.')}}>Reset scans</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Crop</th><th>Field</th><th>Finding</th><th>Severity</th><th>Health</th><th>Status</th><th>Action</th></tr></thead><tbody>{scans.map(s=><tr key={s.id}><td>{new Date(s.created).toLocaleString()}</td><td>{s.crop}</td><td>{s.field}</td><td>{s.disease||s.pest||'Healthy'}</td><td>{pill(s.severity)}</td><td>{s.health}</td><td>{pill(s.status)}</td><td>{s.status==='open'?<button className="btn secondary" onClick={()=>setScanStatus(s.id,'treated')}>Treat</button>:s.status==='treated'?<button className="btn secondary" onClick={()=>setScanStatus(s.id,'resolved')}>Resolve</button>:<span className="note">Complete</span>}</td></tr>)}</tbody></table></div></div><div className="card" style={{marginTop:16}}><h2>Treatment log</h2>{treatments.length?<div className="list">{treatments.map(t=><div className="row" key={t.id}><div><strong>{t.action}</strong><br/><span>{t.notes}</span></div><span>{new Date(t.created).toLocaleDateString()}</span></div>)}</div>:<div className="empty">Treatment records will appear here.</div>}</div></section>
  <section className={`section ${section==='admin'?'active':''}`}><div className="grid two"><div className="card">{!admin?<><h2>Admin sign in</h2><form className="form" onSubmit={login}><input className="input" placeholder="Username" value={user} onChange={e=>setUser(e.target.value)}/><input className="input" type="password" placeholder="Password" value={pass} onChange={e=>setPass(e.target.value)}/><button className="btn">Sign in</button><p className="note">Demo credentials: <b>admin</b> / <b>cropdoctor</b></p></form></>:<><h2>Admin control center</h2><p className="note">Resolve alerts and move open scans through the treatment workflow.</p><div className="toolbar"><button className="btn secondary" onClick={logout}>Sign out</button><button className="btn secondary" onClick={resetDemo}>Reset all demo data</button></div><div className="list">{alerts.map(a=><div className="row" key={a.id}><div><strong>{a.title}</strong><br/><span>{a.message}</span></div>{a.status==='active'?<button className="btn" onClick={()=>resolveAlert(a.id)}>Resolve</button>:pill('resolved')}</div>)}</div></>}</div><div className="card"><h2>System status</h2><div className="list"><div className="row"><strong>Frontend</strong>{pill('healthy')}</div><div className="row"><strong>Persistence</strong><span>Browser localStorage</span></div><div className="row"><strong>AI mode</strong><span>Deterministic demo</span></div><div className="row"><strong>Deployment</strong><span>Vercel compatible</span></div></div></div></div></section>
  </main><nav className="mobile-nav">{nav.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label.split(' ')[0]}</button>)}</nav>{toast&&<div className="toast">{toast}</div>}
 </div>
}
